"""Migracion_inicial

Revision ID: 711c58348a91
Revises: 
Create Date: 2026-08-15 23:56:43.686046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '711c58348a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_nodos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('aetitle', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglas_mapeo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_dicom', sa.String(length=20), nullable=False),
    sa.Column('nombre_dicom', sa.String(length=100), nullable=True),
    sa.Column('campo_hl7', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trazabilidad_integracion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.Enum('INGRESADO', 'TRANSFORMADO', 'COMPLETADO', 'ERROR_EMISION', 'ERROR_PERMANENTE', name='estadotransaccion'), nullable=False),
    sa.Column('payload_dicom', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_hl7', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_index('idx_orden_unica', 'trazabilidad_integracion', ['accession_number', 'study_instance_uid'], unique=True)
    op.create_index(op.f('ix_trazabilidad_integracion_accession_number'), 'trazabilidad_integracion', ['accession_number'], unique=False)
    op.create_index(op.f('ix_trazabilidad_integracion_study_instance_uid'), 'trazabilidad_integracion', ['study_instance_uid'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_trazabilidad_integracion_study_instance_uid'), table_name='trazabilidad_integracion')
    op.drop_index(op.f('ix_trazabilidad_integracion_accession_number'), table_name='trazabilidad_integracion')
    op.drop_index('idx_orden_unica', table_name='trazabilidad_integracion')
    op.drop_table('trazabilidad_integracion')
    op.drop_table('reglas_mapeo')
    op.drop_table('configuracion_nodos')
    # ### end Alembic commands ###
