"""creacion_esquema_trazabilidad

Revision ID: 854f3c13d477
Revises: f18bf6a077ad
Create Date: 2026-08-18 15:35:38.915062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '854f3c13d477'
down_revision: Union[str, Sequence[str], None] = 'f18bf6a077ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_trazabilidad_estado_fecha'), table_name='registro_trazabilidad')
    op.drop_index(op.f('idx_trazabilidad_hl7_gin'), table_name='registro_trazabilidad', postgresql_using='gin')
    op.drop_index(op.f('idx_trazabilidad_payload_gin'), table_name='registro_trazabilidad', postgresql_using='gin')
    op.drop_index(op.f('ix_registro_trazabilidad_accession_number'), table_name='registro_trazabilidad')
    op.drop_index(op.f('ix_registro_trazabilidad_correlation_id'), table_name='registro_trazabilidad')
    op.drop_index(op.f('ix_registro_trazabilidad_created_at'), table_name='registro_trazabilidad')
    op.drop_index(op.f('ix_registro_trazabilidad_estado'), table_name='registro_trazabilidad')
    op.drop_index(op.f('ix_registro_trazabilidad_patient_id'), table_name='registro_trazabilidad')
    op.drop_table('registro_trazabilidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_trazabilidad',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('accession_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('modalidad', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('INGRESADO', 'TRANSFORMADO', 'COMPLETADO', 'ERROR_EMISION', 'ERROR_PERMANENTE', name='estado_mensaje_enum'), autoincrement=False, nullable=False),
    sa.Column('reintentos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload_dicom_raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payload_hl7', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detalles_error', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('registro_trazabilidad_pkey'))
    )
    op.create_index(op.f('ix_registro_trazabilidad_patient_id'), 'registro_trazabilidad', ['patient_id'], unique=False)
    op.create_index(op.f('ix_registro_trazabilidad_estado'), 'registro_trazabilidad', ['estado'], unique=False)
    op.create_index(op.f('ix_registro_trazabilidad_created_at'), 'registro_trazabilidad', ['created_at'], unique=False)
    op.create_index(op.f('ix_registro_trazabilidad_correlation_id'), 'registro_trazabilidad', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_registro_trazabilidad_accession_number'), 'registro_trazabilidad', ['accession_number'], unique=False)
    op.create_index(op.f('idx_trazabilidad_payload_gin'), 'registro_trazabilidad', ['payload_dicom_raw'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_trazabilidad_hl7_gin'), 'registro_trazabilidad', ['payload_hl7'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_trazabilidad_estado_fecha'), 'registro_trazabilidad', ['estado', 'created_at'], unique=False)
    # ### end Alembic commands ###
