"""Creacion tabla trazabilidad_transacciones

Revision ID: c1630e1a02e1
Revises: 
Create Date: 2026-08-15 09:36:42.742301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1630e1a02e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trazabilidad_transacciones',
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('INGRESADO', 'TRANSFORMADO', 'COMPLETADO', 'ERROR_EMISION', 'ERROR_PERMANENTE', name='estadotransaccion'), nullable=False),
    sa.Column('payloads', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auditoria_historica', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_ingesta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trazabilidad_transacciones')
    # ### end Alembic commands ###
