"""cambio_payload_hl7_a_jsonb

Revision ID: f18bf6a077ad
Revises: ae69530d9b75
Create Date: 2026-08-16 18:13:45.040669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18bf6a077ad'
down_revision: Union[str, Sequence[str], None] = 'ae69530d9b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registro_trazabilidad', 'payload_hl7',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
                postgresql_using='to_jsonb(payload_hl7)')
    op.create_index('idx_trazabilidad_hl7_gin', 'registro_trazabilidad', ['payload_hl7'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trazabilidad_hl7_gin', table_name='registro_trazabilidad', postgresql_using='gin')
    op.alter_column('registro_trazabilidad', 'payload_hl7',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
